### ISSUE TITLE
[CLOSED] mcf_upload_cli fails to compile on arch with boost 1.53.0

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#533]
_Issue by **[matthiaskrgr](https://github.com/matthiaskrgr)** from Monday Apr 01, 2013 at 13:14 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/533_

---

[ 99%] Built target crashdlg
[ 99%] Built target desura_bittest
Linking CXX executable mcf_upload_cli
../../shared/usercore/libusercore.so: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code_)'
collect2: error: ld returned 1 exit status
make[2]: *_\* [src/tools/mcf_upload_cli/mcf_upload_cli] Error 1
make[1]: **\* [src/tools/mcf_upload_cli/CMakeFiles/mcf_upload_cli.dir/all] Error 2
make: **\* [all] Error 2
